from enum import Enum

class IncidentSeverity(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"

class IncidentStatus(str, Enum):
    OPEN = "OPEN"
    INVESTIGATING = "INVESTIGATING"
    REMEDIATION_PROPOSED = "REMEDIATION_PROPOSED"
    REMEDIATION_IN_PROGRESS = "REMEDIATION_IN_PROGRESS"
    VERIFYING = "VERIFYING"
    RESOLVED = "RESOLVED"
    CLOSED = "CLOSED"

class EntityType(str, Enum):
    EC2_INSTANCE = "EC2_INSTANCE"
    LAMBDA_FUNCTION = "LAMBDA_FUNCTION"
    ECS_SERVICE = "ECS_SERVICE"
    SECURITY_GROUP = "SECURITY_GROUP"
    COCKROACH_NODE = "COCKROACH_NODE"
    IAM_ROLE = "IAM_ROLE"
    VPC_SUBNET = "VPC_SUBNET"

class RemediationStatus(str, Enum):
    DRAFT = "DRAFT"
    VALIDATING = "VALIDATING"
    AWAITING_APPROVAL = "AWAITING_APPROVAL"
    PENDING_APPROVAL = "PENDING_APPROVAL"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"
    READY_FOR_EXECUTION = "READY_FOR_EXECUTION"
    EXECUTING = "EXECUTING"
    EXECUTED = "EXECUTED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    VERIFIED_SUCCESS = "VERIFIED_SUCCESS"
    VERIFIED_FAILURE = "VERIFIED_FAILURE"
    ROLLED_BACK = "ROLLED_BACK"

class AgentStepStatus(str, Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"

class TrustLevel(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    VERIFIED_GOLD = "VERIFIED_GOLD"
