FROM node:20-alpine

WORKDIR /app/apps/web

COPY apps/web/package*.json ./
RUN npm install

COPY apps/web ./
RUN npm run build

EXPOSE 3000

ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

CMD ["npm", "start"]
