FROM node:20-alpine

WORKDIR /app

COPY apps/web/package*.json ./apps/web/

WORKDIR /app/apps/web
RUN npm install

COPY apps/web ./

EXPOSE 3000

ENV NEXT_TELEMETRY_DISABLED=1

CMD ["npm", "run", "dev"]
