"""sync schemas - create remaining missing tables and add missing columns

Revision ID: 005_sync_schemas
Revises: 004_cockroach_native_vector
Create Date: 2026-08-18

The previous autogenerated migration partially executed (non-transactional DDL
in CockroachDB means DDL committed even though the migration script failed).
So as of 004, these tables already exist in the DB:
  sentinel_instances, sentinel_events, sentinel_alerts, sentinel_decisions,
  sentinel_runs, sentinel_policies, agent_decisions, execution_locks,
  remediation_executions, learned_lessons, memory_candidates, memory_feedback,
  memory_regressions, replay_runs

This migration creates only the remaining missing tables and adds the columns
that are not yet in institutional_memory_vectors and remediation_plans.
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import app.db.types

# revision identifiers, used by Alembic.
revision: str = '005_sync_schemas'
down_revision: Union[str, None] = '004_cockroach_native_vector'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ────────────────────────────────────────────────────
    # Tables that DO NOT yet exist in the DB
    # ────────────────────────────────────────────────────

    # 1. sentinel_incident_links (FK → sentinel_alerts.alert_id, incidents.id)
    op.create_table(
        'sentinel_incident_links',
        sa.Column('alert_id', sa.String(255), nullable=False),
        sa.Column('incident_id', sa.String(), nullable=False),
        sa.Column('relationship', sa.String(100), nullable=False),
        sa.Column('confidence', sa.Float(), nullable=False),
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['alert_id'], ['sentinel_alerts.alert_id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_sentinel_incident_links_alert_id', 'sentinel_incident_links', ['alert_id'], unique=False)
    op.create_index('ix_sentinel_incident_links_incident_id', 'sentinel_incident_links', ['incident_id'], unique=False)

    # 2. execution_step_records (FK → remediation_executions.id)
    op.create_table(
        'execution_step_records',
        sa.Column('execution_id', sa.String(), nullable=False),
        sa.Column('plan_step_id', sa.String(255), nullable=False),
        sa.Column('step_order', sa.Integer(), nullable=False),
        sa.Column('action_type', sa.String(100), nullable=False),
        sa.Column('target_resource', sa.String(512), nullable=False),
        sa.Column('status', sa.String(50), nullable=False),
        sa.Column('idempotency_key', sa.String(255), nullable=False),
        sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('attempt_count', sa.Integer(), nullable=False),
        sa.Column('request_id', sa.String(255), nullable=True),
        sa.Column('result_summary', sa.Text(), nullable=True),
        sa.Column('failure_reason', sa.Text(), nullable=True),
        sa.Column('pre_state', sa.JSON(), nullable=False),
        sa.Column('post_state', sa.JSON(), nullable=False),
        sa.Column('compensation_status', sa.String(50), nullable=False),
        sa.Column('verification_status', sa.String(50), nullable=False),
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['execution_id'], ['remediation_executions.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_execution_step_records_execution_id', 'execution_step_records', ['execution_id'], unique=False)
    op.create_index('ix_execution_step_records_idempotency_key', 'execution_step_records', ['idempotency_key'], unique=False)

    # 3. execution_events (FK → remediation_executions.id)
    op.create_table(
        'execution_events',
        sa.Column('execution_id', sa.String(), nullable=False),
        sa.Column('step_id', sa.String(255), nullable=True),
        sa.Column('event_type', sa.String(100), nullable=False),
        sa.Column('actor', sa.String(100), nullable=False),
        sa.Column('request_id', sa.String(255), nullable=True),
        sa.Column('summary', sa.Text(), nullable=False),
        sa.Column('metadata_json', sa.JSON(), nullable=False),
        sa.Column('severity', sa.String(50), nullable=False),
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['execution_id'], ['remediation_executions.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_execution_events_execution_id', 'execution_events', ['execution_id'], unique=False)
    op.create_index('ix_execution_events_event_type', 'execution_events', ['event_type'], unique=False)

    # 4. remediation_outcomes (FK → incidents, remediation_plans, remediation_executions)
    op.create_table(
        'remediation_outcomes',
        sa.Column('incident_id', sa.String(), nullable=False),
        sa.Column('plan_id', sa.String(), nullable=False),
        sa.Column('execution_id', sa.String(), nullable=False),
        sa.Column('execution_status', sa.String(50), nullable=False),
        sa.Column('verification_status', sa.String(50), nullable=False),
        sa.Column('incident_recovery_status', sa.String(50), nullable=False),
        sa.Column('outcome_classification', sa.String(100), nullable=False),
        sa.Column('effectiveness_score', sa.Float(), nullable=False),
        sa.Column('duration_seconds', sa.Float(), nullable=False),
        sa.Column('executed_steps_count', sa.Integer(), nullable=False),
        sa.Column('failed_steps_count', sa.Integer(), nullable=False),
        sa.Column('compensated_steps_count', sa.Integer(), nullable=False),
        sa.Column('rollback_performed', sa.Boolean(), nullable=False),
        sa.Column('rollback_successful', sa.Boolean(), nullable=False),
        sa.Column('before_state', sa.JSON(), nullable=False),
        sa.Column('after_state', sa.JSON(), nullable=False),
        sa.Column('recovery_metrics', sa.JSON(), nullable=False),
        sa.Column('evidence_refs', sa.JSON(), nullable=False),
        sa.Column('confidence', sa.Float(), nullable=False),
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['plan_id'], ['remediation_plans.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['execution_id'], ['remediation_executions.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_remediation_outcomes_incident_id', 'remediation_outcomes', ['incident_id'], unique=False)
    op.create_index('ix_remediation_outcomes_plan_id', 'remediation_outcomes', ['plan_id'], unique=False)
    op.create_index('ix_remediation_outcomes_execution_id', 'remediation_outcomes', ['execution_id'], unique=False)
    op.create_index('ix_remediation_outcomes_outcome_classification', 'remediation_outcomes', ['outcome_classification'], unique=False)

    # 5. replay_scenarios (FK → replay_runs.id)
    op.create_table(
        'replay_scenarios',
        sa.Column('replay_id', sa.String(), nullable=False),
        sa.Column('completeness_score', sa.Float(), nullable=False),
        sa.Column('infrastructure_state', sa.JSON(), nullable=False),
        sa.Column('incident_state', sa.JSON(), nullable=False),
        sa.Column('telemetry_state', sa.JSON(), nullable=False),
        sa.Column('memory_context', sa.JSON(), nullable=False),
        sa.Column('scenario_hash', sa.String(255), nullable=False),
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['replay_id'], ['replay_runs.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_replay_scenarios_replay_id', 'replay_scenarios', ['replay_id'], unique=False)
    op.create_index('ix_replay_scenarios_scenario_hash', 'replay_scenarios', ['scenario_hash'], unique=False)

    # 6. replay_step_records (FK → replay_runs.id)
    op.create_table(
        'replay_step_records',
        sa.Column('replay_id', sa.String(), nullable=False),
        sa.Column('step_order', sa.Integer(), nullable=False),
        sa.Column('agent_name', sa.String(100), nullable=False),
        sa.Column('action_type', sa.String(100), nullable=False),
        sa.Column('target_resource', sa.String(512), nullable=False),
        sa.Column('input_summary', sa.Text(), nullable=False),
        sa.Column('output_summary', sa.Text(), nullable=False),
        sa.Column('simulated_pre_state', sa.JSON(), nullable=False),
        sa.Column('simulated_post_state', sa.JSON(), nullable=False),
        sa.Column('evidence_refs', sa.JSON(), nullable=False),
        sa.Column('confidence', sa.Float(), nullable=False),
        sa.Column('status', sa.String(50), nullable=False),
        sa.Column('duration_ms', sa.Float(), nullable=False),
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['replay_id'], ['replay_runs.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_replay_step_records_replay_id', 'replay_step_records', ['replay_id'], unique=False)

    # 7. replay_differences (FK → replay_runs.id)
    op.create_table(
        'replay_differences',
        sa.Column('replay_id', sa.String(), nullable=False),
        sa.Column('category', sa.String(100), nullable=False),
        sa.Column('historical_value', sa.JSON(), nullable=False),
        sa.Column('predicted_value', sa.JSON(), nullable=False),
        sa.Column('severity', sa.String(50), nullable=False),
        sa.Column('explanation', sa.Text(), nullable=False),
        sa.Column('evidence_refs', sa.JSON(), nullable=False),
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['replay_id'], ['replay_runs.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_replay_differences_replay_id', 'replay_differences', ['replay_id'], unique=False)
    op.create_index('ix_replay_differences_category', 'replay_differences', ['category'], unique=False)

    # 8. simulation_mutations (FK → replay_runs.id)
    op.create_table(
        'simulation_mutations',
        sa.Column('replay_id', sa.String(), nullable=False),
        sa.Column('resource_id', sa.String(512), nullable=False),
        sa.Column('action_type', sa.String(100), nullable=False),
        sa.Column('pre_state', sa.JSON(), nullable=False),
        sa.Column('post_state', sa.JSON(), nullable=False),
        sa.Column('simulated_only', sa.Boolean(), nullable=False),
        sa.Column('reversible', sa.Boolean(), nullable=False),
        sa.Column('mutation_hash', sa.String(255), nullable=False),
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['replay_id'], ['replay_runs.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_simulation_mutations_replay_id', 'simulation_mutations', ['replay_id'], unique=False)
    op.create_index('ix_simulation_mutations_resource_id', 'simulation_mutations', ['resource_id'], unique=False)
    op.create_index('ix_simulation_mutations_mutation_hash', 'simulation_mutations', ['mutation_hash'], unique=False)

    # 9. memory_consolidations (FK → memory_candidates.id)
    op.create_table(
        'memory_consolidations',
        sa.Column('candidate_id', sa.String(), nullable=False),
        sa.Column('target_memory_id', sa.String(255), nullable=True),
        sa.Column('action', sa.String(50), nullable=False),
        sa.Column('reason', sa.Text(), nullable=False),
        sa.Column('previous_memory_ids', sa.JSON(), nullable=False),
        sa.Column('evidence_refs', sa.JSON(), nullable=False),
        sa.Column('confidence_before', sa.Float(), nullable=False),
        sa.Column('confidence_after', sa.Float(), nullable=False),
        sa.Column('actor', sa.String(100), nullable=False),
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['candidate_id'], ['memory_candidates.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_memory_consolidations_candidate_id', 'memory_consolidations', ['candidate_id'], unique=False)
    op.create_index('ix_memory_consolidations_target_memory_id', 'memory_consolidations', ['target_memory_id'], unique=False)
    op.create_index('ix_memory_consolidations_action', 'memory_consolidations', ['action'], unique=False)

    # ────────────────────────────────────────────────────
    # Add missing columns to institutional_memory_vectors
    # (existing cols: id, title, content, entity_type, entity_id, incident_id,
    #  embedding, metadata_json, trust_level, created_at, updated_at,
    #  redacted_content, memory_type, evidence_references)
    # ────────────────────────────────────────────────────
    op.add_column('institutional_memory_vectors',
        sa.Column('source_execution_id', sa.String(255), nullable=True))
    op.add_column('institutional_memory_vectors',
        sa.Column('confidence', sa.Float(), nullable=False, server_default='0.75'))
    op.add_column('institutional_memory_vectors',
        sa.Column('memory_status', sa.String(50), nullable=False, server_default='ACTIVE'))
    op.add_column('institutional_memory_vectors',
        sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')))
    op.add_column('institutional_memory_vectors',
        sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True))
    op.add_column('institutional_memory_vectors',
        sa.Column('superseded_by', sa.String(255), nullable=True))
    op.add_column('institutional_memory_vectors',
        sa.Column('applicability_conditions', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('institutional_memory_vectors',
        sa.Column('non_applicability_conditions', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('institutional_memory_vectors',
        sa.Column('usage_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('institutional_memory_vectors',
        sa.Column('successful_usage_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('institutional_memory_vectors',
        sa.Column('failed_usage_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('institutional_memory_vectors',
        sa.Column('last_validated_at', sa.DateTime(timezone=True), nullable=True))

    op.create_index('ix_institutional_memory_vectors_source_execution_id',
        'institutional_memory_vectors', ['source_execution_id'], unique=False)
    op.create_index('ix_institutional_memory_vectors_memory_status',
        'institutional_memory_vectors', ['memory_status'], unique=False)
    op.create_index('ix_institutional_memory_vectors_superseded_by',
        'institutional_memory_vectors', ['superseded_by'], unique=False)

    # ────────────────────────────────────────────────────
    # Add missing columns to remediation_plans
    # (existing cols: id, incident_id, title, explanation, status,
    #  idempotency_key, approved_by, approved_at, rejection_reason,
    #  estimated_risk, requires_human_approval, created_at, updated_at)
    # ────────────────────────────────────────────────────
    op.add_column('remediation_plans',
        sa.Column('investigation_run_id', sa.String(255), nullable=True))
    op.add_column('remediation_plans',
        sa.Column('version', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('remediation_plans',
        sa.Column('root_cause_hypothesis_id', sa.String(100), nullable=True))
    op.add_column('remediation_plans',
        sa.Column('confidence', sa.Float(), nullable=False, server_default='0.5'))
    op.add_column('remediation_plans',
        sa.Column('compatibility_score', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('remediation_plans',
        sa.Column('compatibility_classification', sa.String(100), nullable=False, server_default='UNKNOWN'))
    op.add_column('remediation_plans',
        sa.Column('risk_score', sa.Float(), nullable=False, server_default='0.1'))
    op.add_column('remediation_plans',
        sa.Column('blast_radius', sa.String(50), nullable=False, server_default='LOCAL'))
    op.add_column('remediation_plans',
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('remediation_plans',
        sa.Column('approval_gate', sa.JSON(), nullable=False, server_default='{}'))
    op.add_column('remediation_plans',
        sa.Column('safety_checks', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('remediation_plans',
        sa.Column('rollback_plan', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('remediation_plans',
        sa.Column('verification_plan', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('remediation_plans',
        sa.Column('evidence_refs', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('remediation_plans',
        sa.Column('historical_precedent_refs', sa.JSON(), nullable=False, server_default='[]'))

    op.create_index('ix_remediation_plans_investigation_run_id',
        'remediation_plans', ['investigation_run_id'], unique=False)
    op.create_index('ix_remediation_plans_incident_id',
        'remediation_plans', ['incident_id'], unique=False)
    op.create_index('ix_remediation_plans_status',
        'remediation_plans', ['status'], unique=False)


def downgrade() -> None:
    op.drop_index('ix_remediation_plans_status', table_name='remediation_plans')
    op.drop_index('ix_remediation_plans_incident_id', table_name='remediation_plans')
    op.drop_index('ix_remediation_plans_investigation_run_id', table_name='remediation_plans')
    for col in ['historical_precedent_refs', 'evidence_refs', 'verification_plan',
                'rollback_plan', 'safety_checks', 'approval_gate', 'expires_at',
                'blast_radius', 'risk_score', 'compatibility_classification',
                'compatibility_score', 'confidence', 'root_cause_hypothesis_id',
                'version', 'investigation_run_id']:
        op.drop_column('remediation_plans', col)

    op.drop_index('ix_institutional_memory_vectors_superseded_by', table_name='institutional_memory_vectors')
    op.drop_index('ix_institutional_memory_vectors_memory_status', table_name='institutional_memory_vectors')
    op.drop_index('ix_institutional_memory_vectors_source_execution_id', table_name='institutional_memory_vectors')
    for col in ['last_validated_at', 'failed_usage_count', 'successful_usage_count',
                'usage_count', 'non_applicability_conditions', 'applicability_conditions',
                'superseded_by', 'valid_to', 'valid_from', 'memory_status',
                'confidence', 'source_execution_id']:
        op.drop_column('institutional_memory_vectors', col)

    op.drop_table('memory_consolidations')
    op.drop_table('simulation_mutations')
    op.drop_table('replay_differences')
    op.drop_table('replay_step_records')
    op.drop_table('replay_scenarios')
    op.drop_table('remediation_outcomes')
    op.drop_table('execution_events')
    op.drop_table('execution_step_records')
    op.drop_table('sentinel_incident_links')
